### ISSUE TITLE
Uhm, why did you create this?

### ISSUE THREAD

**Issue by jimmywarting** [node-fetch/btoa-lite#2]
btoa exist everywhere now basically. it's global in nodejs since v16.

https://nodejs.org/dist/latest/docs/api/globals.html#btoadata

v16 is LTS right now...

And there is also kind of already one out there that dose the same thing: https://github.com/hughsk/btoa-lite 

also using base64 should best be avoided, it's better to just deal with TypedArrays / Blobs instead of increasing the payload/memory with 33% more data

**Comment by Richienb** [comment]
> And there is also kind of already one out there that dose the same thing: [hughsk/btoa-lite](https://github.com/hughsk/btoa-lite)

This package exists because https://github.com/hughsk/btoa-lite/pull/3 never ended up getting merged. https://github.com/hughsk/btoa-lite/pull/3 replaced `new Buffer` (which throws a deprecation warning) with `Buffer.from`.

> btoa exist everywhere now basically. it's global in nodejs since v16.

Somehow, the docs don't recommend using `btoa`.

> also using base64 should best be avoided, it's better to just deal with TypedArrays / Blobs instead of increasing the payload/memory with 33% more data

Yes

> Uhm, why did you create this?

I don't remember anymore. There might be some clues in https://github.com/hughsk/btoa-lite/pull/3.
I do remember that at some point, we got the `node-fetch` org after planning to publish it there for a couple years, so I just went ahead with it.

So, in theory, I think this makes this package the only one to wrap the "correct" way of doing `btoa`. Do you wanna do anything with it?
